export const UPDATE_SIGHTINGS = "UPDATE_SIGHTINGS";
export const REMOVE_SIGHTING = "REMOVE_SIGHTING";
export const SET_CURRENT_SIGHTING = "SET_CURRENT_SIGHTING";
export const ADD_SIGHTING = "ADD_SIGHTING";
export const LOADING = "LOADING";

export const ADD_FAVORITE = "ADD_FAVORITE";
export const REMOVE_FAVORITE = "REMOVE_FAVORITE";
export const UPDATE_FAVORITES = "UPDATE_FAVORITES";
